cookie:
  expiry_days: 30
  key:  key # To be filled with any string
  name: name # To be filled with any string
credentials:
  usernames:
    admin.aichatbot:
      email: admin@abbank.vn
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Admin
      last_name: Admin
      logged_in: False # Will be managed automatically
      password: $2b$12$dtTKq9U0B4.NFDMRRDjuRedPL/XQQHR3XYUmeyzdv1OS/tiY0AYDK # Will be hashed automatically
      roles: # Optional
      - admin
    ops.aichatbot:
      email: user@abbank.vn
      failed_login_attempts: 0 # Will be managed automatically
      first_name: User
      last_name: User
      logged_in: False # Will be managed automatically
      password: $2b$12$dtTKq9U0B4.NFDMRRDjuRedPL/XQQHR3XYUmeyzdv1OS/tiY0AYDK  # Will be hashed automatically
      roles: # Optional
      - editor
      - viewer